env:
  global:
    - CC_TEST_REPORTER_ID=
language: node_js
node_js:
  - "8.11.4"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: yarn install && cd test && yarn test:coverage
after_script:
  - cd ..
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT